# Daily Processing Report
# Generates a daily report of processed issues
name: Daily Processing Report

on:
  schedule:
    - cron: '0 9 * * *'  # 毎日9時 (UTC)
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Report
        uses: actions/github-script@v7
        with:
          script: |
            const oneDayAgo = new Date(Date.now() - 24*60*60*1000).toISOString();
            
            // 処理済みIssue取得
            const processed = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'claude-code-completed',
              since: oneDayAgo,
              state: 'all'
            });
            
            // 失敗Issue取得
            const failed = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'claude-code-failed',
              since: oneDayAgo,
              state: 'all'
            });
            
            // 待機中Issue取得
            const waiting = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'claude-code-waiting',
              state: 'open'
            });
            
            // 処理中Issue取得
            const processing = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'claude-code-processing',
              state: 'open'
            });
            
            // レポート作成
            const totalProcessed = processed.data.length + failed.data.length;
            const successRate = totalProcessed > 0 
              ? (processed.data.length / totalProcessed * 100).toFixed(1)
              : 0;
              
            const report = `# 📊 Daily Processing Report
            
**Date**: ${new Date().toLocaleDateString()}
**Time**: ${new Date().toLocaleTimeString()} UTC
            
## Summary
- ✅ Processed: ${processed.data.length}
- ❌ Failed: ${failed.data.length}
- ⏳ Waiting: ${waiting.data.length}
- 🔄 Processing: ${processing.data.length}
- 🎯 Success Rate: ${successRate}%
            
## Details

### Successfully Processed
${processed.data.length > 0 
  ? processed.data.map(i => `- #${i.number}: ${i.title}`).join('\n')
  : '- No issues processed successfully'}
            
### Failed Processing
${failed.data.length > 0
  ? failed.data.map(i => `- #${i.number}: ${i.title}`).join('\n')
  : '- No failed issues'}
  
### Currently Waiting
${waiting.data.length > 0
  ? waiting.data.map(i => `- #${i.number}: ${i.title}`).join('\n')
  : '- No issues waiting'}
  
### Currently Processing
${processing.data.length > 0
  ? processing.data.map(i => `- #${i.number}: ${i.title}`).join('\n')
  : '- No issues currently processing'}

---
*Report generated by GitHub Actions Label Processor*
`;
            
            // Issue作成
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Daily Report - ${new Date().toLocaleDateString()}`,
              body: report,
              labels: ['report', 'automated']
            });